---
- name: Download EPEL Repo rpm package
  get_url: url=http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm dest=/tmp/epel-release-6-8.noarch.rpm

- name: Install EPEL Repo rpm package
  yum: name=/tmp/epel-release-6-8.noarch.rpm state=present

- name: Install required Ansible libraries
  yum: name={{ item }} state=present
  with_items:
    - libselinux-python
    - MySQL-python

- name: Update /etc/hosts with server hostname
  template: src=hosts.j2 dest=/etc/hosts

- name: Set specified timezone
  file: src=/usr/share/zoneinfo/{{ default_timezone }} dest=/etc/localtime state=link force=yes